### ISSUE TITLE
Shopify CAPI

### ISSUE THREAD

**Issue by ap0l0** [stape-io/shopify-gtm-container-templates#1]
Hi @Bukashk0zzz , 

Is this implementation completed? Not a developer but I can assist you in the missing parameters such as External ID, etc.

Basically, making it more oriented to e-commerce (Shopify, etc.)

**Comment by Bukashk0zzz** [comment]
Thanks for your issue and proposal.
But I am not finished work on Shopify -> GTM SS -> Facebook CAPI integration. I am working on it at the moment. 
When I finish work and made the blog post, I will add all necessary info to Readme.
